# General
exp_name: clip_vitb32    # name of the experiment
clip_model_name: ViT-B/32  # name of the CLIP model
resume_experiment: false    # resume training and logging of the experiment with the same name if it exists
seed: 42    # seed for reproducibility
validate: false   # if True, validate the model

# Data
dataroot: ""   # base path for the datasets
dataset_name: ""   # name of the dataset
split: ""    # split of the dataset to use. By default, it is the same split of the paper

# Optimization
learning_rate: !!float 2e-2   # learning rate
batch_size: 64    # batch size
oti_steps: 150   # optimization steps
num_pseudo_tokens: 1   # number of pseudo tokens
save_frequency: 25   # frequency of saving the model

# Loss
weight_decay: 0.01   # weight decay
template_sentence: 'a photo of {}'   # which templates to use

# Miscellaneous
use_open_clip: false   # if True, use open clip
open_clip_pretrained: ""   # open clip pretrained model

